name: rag_faq_document
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.1.1
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^11.4.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  validators: ^3.0.0
  flutter_dotenv: ^5.1.0
  file_picker: ^10.1.2
  flutter_native_splash: ^2.4.4
  infinite_scroll_pagination: ^5.0.0
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1
  loader_overlay: ^5.0.0
  lottie: ^3.3.1
  flutter_pdfview: ^1.4.0+1
  pdfx: ^2.9.1
  dio: ^5.8.0+1
  skeletonizer: ^1.4.3
  path_provider: ^2.1.5
  flutter_cached_pdfview: ^0.4.3
  cached_network_image: ^3.4.1
  web_socket_channel: ^3.0.3
  mockito: ^5.4.6
  riverpod_test: ^0.1.9
  intl: ^0.20.2
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/lottie/ai_animation.json
    - assets/lottie/difficult.json
    - assets/lottie/happy.json
    - assets/lottie/search.json
    - assets/lottie/logo2.json
    - assets/lottie/load_bg.json
    - .env
